// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "lvgl.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_omercount = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_omercount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_omercount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_omercount, -9);
    lv_obj_set_y(ui_omercount, 14);
    lv_obj_set_align(ui_omercount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_omercount, "Tonight We Count");

    ui_omernumber = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_omernumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_omernumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_omernumber, -7);
    lv_obj_set_y(ui_omernumber, 45);
    lv_obj_set_align(ui_omernumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_omernumber, "text");
    lv_obj_set_style_text_color(ui_omernumber, lv_color_hex(0xF31212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_omernumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_omernumber, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

}
