// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_main_screen_init(void)
{
    ui_main = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_main, lv_color_hex(0x3CB0CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_main);
    lv_obj_set_width(ui_TextArea1, 218);
    lv_obj_set_height(ui_TextArea1, 102);
    lv_obj_set_x(ui_TextArea1, 1);
    lv_obj_set_y(ui_TextArea1, -99);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea1, 2048);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");



    ui_omerCounter = lv_label_create(ui_main);
    lv_obj_set_width(ui_omerCounter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_omerCounter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_omerCounter, -4);
    lv_obj_set_y(ui_omerCounter, 69);
    lv_obj_set_align(ui_omerCounter, LV_ALIGN_CENTER);
    lv_label_set_text(ui_omerCounter, "99");
    lv_obj_set_style_text_color(ui_omerCounter, lv_color_hex(0xEE0B0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_omerCounter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_omerCounter, &ui_font_shantelbignumbers123, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_omerLabel = lv_label_create(ui_main);
    lv_obj_set_width(ui_omerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_omerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_omerLabel, -32);
    lv_obj_set_y(ui_omerLabel, -3);
    lv_obj_set_align(ui_omerLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_omerLabel, "Current Omer Count");

}
